### ISSUE TITLE
Pydantic project dependency not consistent (possibly others too; consider using a singe python packaging model?)

### ISSUE THREAD

**Issue by dotWee** [Tert0/fastapi-framework#161]
**Describe the bug**
It is currently not possible to add `fastapi-framework` to projects using a different pydantic version.
Seems like @dependabot forgot to take care of the `pyproject.toml`, as it still references an outdated pydantic version.

https://github.com/Tert0/fastapi-framework/blob/104202c1857df82001c3281b3def2be9ee40b122/pyproject.toml#L21

https://github.com/Tert0/fastapi-framework/blob/104202c1857df82001c3281b3def2be9ee40b122/requirements.txt#L9

**To Reproduce**
```bash
$ poetry add fastapi-framework
Using version ^1.5.3.3 for fastapi-framework

Updating dependencies
Resolving dependencies... (0.1s)

Because fastapi-framework (1.5.3.3) depends on pydantic (1.10.5)
 and no versions of fastapi-framework match >1.5.3.3,<2.0.0.0, fastapi-framework (>=1.5.3.3,<2.0.0.0) requires pydantic (1.10.5).
So, because ourpoetrypackage depends on both pydantic (^1.10.7) and fastapi-framework (^1.5.3.3), version solving failed.
```

When trying to use the develop branch:

```shell
$ poetry add git+https://github.com/Tert0/fastapi-framework.git#develop
Updating dependencies
Resolving dependencies... (0.0s)

Because fastapi-framework (1.5.3.3) @ git+https://github.com/Tert0/fastapi-framework.git@develop depends on pydantic (1.10.5)
 and ourpoetrypackage depends on pydantic (^1.10.7), fastapi-framework is forbidden.
So, because ourpoetrypackage depends on fastapi-framework (1.5.3.3) @ git+https://github.com/Tert0/fastapi-framework.git@develop, version solving failed.
```

**Expected behavior**
Package `fastapi-framework` can be used together with latest Pydantic & FastAPI versions.

---

(Cheers & thank you for sharing your code! Your open source work is really appreciated!)

**Comment by Tert0** [comment]
The issue with dependabot has been resolved in 706d13a9b9590596773cbb6ce87843814be2e0cc and the Version [v1.5.3.4](https://github.com/Tert0/fastapi-framework/tree/v1.5.3.4) should include these changes.
